logging:
  level: INFO
  loggers:
    com.gradus.statusreport: DEBUG
# configuration to dev environment
server:
  rootPath: '/api/*'
# ----
applicationDataSourceFactory:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: root
  url: jdbc:mysql://127.0.0.1:3306/rental_application
  properties:
    charset: UTF-8
    maxWaitForConnections: 1s
    validationQuery: "/* MyService Health Check */ SELECT 1"
    minSize: 8
    maxSize: 32
    checkConnectionWhileIdle: false
    evictionInterval: 10s
    minIdleTime: 1 minute